# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

### Strategy for the solution:

**Apply the cleaning function to the new combined dataset:**
- load the three raw CSV files;
- cleaning the large dataset;
- merge them

In [3]:
# Your code goes here

# Fűzd össze őket a pd.concat([df1, df2, df3], ignore_index=True) függvénnyel.
# Vizsgáld meg a kapott összképet (pl. .info(), .head(), oszlopnevek ellenőrzése).

import pandas as pd
import numpy as np

df1 = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv')

df2 = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv')

df3 = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv')

In [4]:
print("Shape of dataframes:")
display(f"Shape df1: {df1.shape}")
display(f"Shape df2: {df2.shape}")
display(f"Shape df3: {df3.shape}")


print("\nInfo about dataframes:")

display(f"Info df1: {df1.info()}")
display(f"Info df2: {df2.info()}")
display(f"Info df3: {df3.info()}")


print("\nIHead of dataframes:")

display(f"Head df1: {df1.head()}")
display(f"Head df2: {df2.head()}")
display(f"Head df3: {df3.head()}")

Shape of dataframes:

'Shape df1: (4008, 11)'

'Shape df2: (996, 11)'

'Shape df3: (7070, 11)'

Info about dataframes:
<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   str
 1   ST                         1071 non-null   str
 2   GENDER                     954 non-null    str
 3   Education                  1071 non-null   str
 4   Customer Lifetime Value    1068 non-null   str
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   str
 8   Policy Type                1071 non-null   str
 9   Vehicle Class              1071 non-null   str
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), str(8)
memory usage: 417.4 KB

'Info df1: None'

<class 'pandas.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   996 non-null    str
 1   ST                         996 non-null    str
 2   GENDER                     991 non-null    str
 3   Education                  996 non-null    str
 4   Customer Lifetime Value    992 non-null    str
 5   Income                     996 non-null    int64
 6   Monthly Premium Auto       996 non-null    int64
 7   Number of Open Complaints  996 non-null    str
 8   Total Claim Amount         996 non-null    float64
 9   Policy Type                996 non-null    str
 10  Vehicle Class              996 non-null    str
dtypes: float64(1), int64(2), str(8)
memory usage: 150.6 KB

'Info df2: None'

<class 'pandas.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   7070 non-null   str
 1   State                      7070 non-null   str
 2   Customer Lifetime Value    7070 non-null   float64
 3   Education                  7070 non-null   str
 4   Gender                     7070 non-null   str
 5   Income                     7070 non-null   int64
 6   Monthly Premium Auto       7070 non-null   int64
 7   Number of Open Complaints  7070 non-null   int64
 8   Policy Type                7070 non-null   str
 9   Total Claim Amount         7070 non-null   float64
 10  Vehicle Class              7070 non-null   str
dtypes: float64(2), int64(3), str(6)
memory usage: 957.0 KB

'Info df3: None'

IHead of dataframes:

'Head df1:   Customer          ST GENDER             Education Customer Lifetime Value  \\\n0  RB50392  Washington    NaN                Master                     NaN   \n1  QZ44356     Arizona      F              Bachelor              697953.59%   \n2  AI49188      Nevada      F              Bachelor             1288743.17%   \n3  WW63253  California      M              Bachelor              764586.18%   \n4  GA49547  Washington      M  High School or Below              536307.65%   \n\n    Income  Monthly Premium Auto Number of Open Complaints     Policy Type  \\\n0      0.0                1000.0                    1/0/00   Personal Auto   \n1      0.0                  94.0                    1/0/00   Personal Auto   \n2  48767.0                 108.0                    1/0/00   Personal Auto   \n3      0.0                 106.0                    1/0/00  Corporate Auto   \n4  36357.0                  68.0                    1/0/00   Personal Auto   \n\n   Vehicle Class  Total Claim Amount  \n0  Four-Door Car            2.704934  \n1  Four-Door Car         1131.464935  \n2   Two-Door Car          566.472247  \n3            SUV          529.881344  \n4  Four-Door Car           17.269323  '

'Head df2:   Customer          ST GENDER Education Customer Lifetime Value  Income  \\\n0  GS98873     Arizona      F  Bachelor              323912.47%   16061   \n1  CW49887  California      F    Master              462680.11%   79487   \n2  MY31220  California      F   College              899704.02%   54230   \n3  UH35128      Oregon      F   College             2580706.30%   71210   \n4  WH52799     Arizona      F   College              380812.21%   94903   \n\n   Monthly Premium Auto Number of Open Complaints  Total Claim Amount  \\\n0                    88                    1/0/00               633.6   \n1                   114                    1/0/00               547.2   \n2                   112                    1/0/00               537.6   \n3                   214                    1/1/00              1027.2   \n4                    94                    1/0/00               451.2   \n\n      Policy Type  Vehicle Class  \n0   Personal Auto  Four-Door Car  \n1    Special Auto            SUV  \n2   Personal Auto   Two-Door Car  \n3   Personal Auto     Luxury Car  \n4  Corporate Auto   Two-Door Car  '

'Head df3:   Customer       State  Customer Lifetime Value             Education Gender  \\\n0  SA25987  Washington              3479.137523  High School or Below      M   \n1  TB86706     Arizona              2502.637401                Master      M   \n2  ZL73902      Nevada              3265.156348              Bachelor      F   \n3  KX23516  California              4455.843406  High School or Below      F   \n4  FN77294  California              7704.958480  High School or Below      M   \n\n   Income  Monthly Premium Auto  Number of Open Complaints    Policy Type  \\\n0       0                   104                          0  Personal Auto   \n1       0                    66                          0  Personal Auto   \n2   25820                    82                          0  Personal Auto   \n3       0                   121                          0  Personal Auto   \n4   30366                   101                          2  Personal Auto   \n\n   Total Claim Amount  Vehicle Class  \n0          499.200000   Two-Door Car  \n1            3.468912   Two-Door Car  \n2          393.600000  Four-Door Car  \n3          699.615192            SUV  \n4          484.800000            SUV  '

In [5]:
import functions
# Cleaning of the columns names with functions.py
df1 = functions.clean_column_names(df1)
df2 = functions.clean_column_names(df2)
df3 = functions.clean_column_names(df3)


print("\nColumns of df1:", df1.columns.tolist())
print("\nColumns of df2:", df2.columns.tolist())
print("\nColumns of df3:", df3.columns.tolist())

Columns of df1: ['customer', 'st', 'gender', 'education', 'customer_lifetime_value', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'policy_type', 'vehicle_class', 'total_claim_amount']

Columns of df2: ['customer', 'st', 'gender', 'education', 'customer_lifetime_value', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'total_claim_amount', 'policy_type', 'vehicle_class']

Columns of df3: ['customer', 'state', 'customer_lifetime_value', 'education', 'gender', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'policy_type', 'total_claim_amount', 'vehicle_class']

In [6]:
import functions

df1 = functions.clean_column_names(df1)
df2 = functions.clean_column_names(df2)
df3 = functions.clean_column_names(df3)

df1 = df1.rename(columns={'st': 'state'})
df2 = df2.rename(columns={'st': 'state'})

In [7]:
# Datatyes
print("Datatypes of df1:")
print(df1.dtypes)

# Missing values
print("\nNumber of missing values (df1):")
print(df1.isna().sum())

Datatypes of df1:
customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value          str
income                       float64
monthly_premium_auto         float64
number_of_open_complaints        str
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

Number of missing values (df1):
customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [8]:
# Datatyes
print("Datatypes of df2:")
print(df2.dtypes)

# Missing values
print("\nNumber of missing values (df2):")
print(df2.isna().sum())

Datatypes of df2:
customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value          str
income                         int64
monthly_premium_auto           int64
number_of_open_complaints        str
total_claim_amount           float64
policy_type                      str
vehicle_class                    str
dtype: object

Number of missing values (df2):
customer                     0
state                        0
gender                       5
education                    0
customer_lifetime_value      4
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
total_claim_amount           0
policy_type                  0
vehicle_class                0
dtype: int64

In [9]:
# Datatyes
print("Datatypes of df3:")
print(df3.dtypes)

# Missing values
print("\nNumber of missing values (df3):")
print(df3.isna().sum())

Datatypes of df3:
customer                         str
state                            str
customer_lifetime_value      float64
education                        str
gender                           str
income                         int64
monthly_premium_auto           int64
number_of_open_complaints      int64
policy_type                      str
total_claim_amount           float64
vehicle_class                    str
dtype: object

Number of missing values (df3):
customer                     0
state                        0
customer_lifetime_value      0
education                    0
gender                       0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
total_claim_amount           0
vehicle_class                0
dtype: int64

In [10]:
# The order of columns from the first DataFrame
target_columns = df1.columns.tolist()

# Rearranging all DataFrames into this order
df2 = df2[target_columns]
df3 = df3[target_columns]

print(df1.dtypes)
print(f"\n{df2.dtypes}")
print(f"\n{df3.dtypes}")

customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value          str
income                       float64
monthly_premium_auto         float64
number_of_open_complaints        str
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value          str
income                         int64
monthly_premium_auto           int64
number_of_open_complaints        str
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value      float64
income                         int64
monthly_premium_auto           int64
number_of_open_complaints      int64
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

### Datatyes
customer, st, gender, education, policy_type, vehicle_class are
Current type :str
Assessment: Appropriate. These are categorical, textual data, for which the string type is the correct choice.

### df1: incorrect data types and fixes:

1. **Customer Lifetime Value (`float` recommended instead of `str`)**
Currently stored as a string (`str`) type because it contains a percentage sign (`%`) or other characters.
Fix: Remove non-numeric characters (e.g., using `.str.replace('%', '')`) and then convert to a floating-point number (`float`).

2. **Number of Open Complaints (`int` recommended instead of `str`)**
Stored as a string (`str`), even though the *number* of complaints should clearly be an integer.
Fix: Handle invalid values ​​or text entries using the `pd.to_numeric(..., errors='coerce')` function, then convert to `int`.

3. Categorical columns (`state`, `gender`, `education`, `policy_type`, `vehicle_class`)
These are currently of type `str` (or `object`), which is appropriate for text/categorical data.
Fix: Standardize the data (e.g., unify case, remove extra whitespace using `.str.strip().str.lower()`). You could also convert these to the `category` data type for better memory efficiency, though storing them as strings (`str`) is also acceptable.
-----

In [11]:
# Customer Lifetime value:

df1['customer_lifetime_value'] = df1['customer_lifetime_value'].map(functions.clean_customer_lifetime_value)
df1['customer_lifetime_value'] = pd.to_numeric(df1['customer_lifetime_value'], errors='coerce')
df2['customer_lifetime_value'] = df2['customer_lifetime_value'].map(functions.clean_customer_lifetime_value)
df2['customer_lifetime_value'] = pd.to_numeric(df2['customer_lifetime_value'], errors='coerce')
df3['customer_lifetime_value'] = df3['customer_lifetime_value'].map(functions.clean_customer_lifetime_value)

print(df1.dtypes)
print(f"\n{df2.dtypes}")
print(f"\n{df3.dtypes}")

customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints        str
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value      float64
income                         int64
monthly_premium_auto           int64
number_of_open_complaints        str
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value      float64
income                         int64
monthly_premium_auto           int64
number_of_open_complaints      int64
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

In [13]:
# Number of open complaints:

# df1 cleaning and transformation
df1['number_of_open_complaints'] = df1['number_of_open_complaints'].map(
    functions.clean_open_complaints
)
df1['number_of_open_complaints'] = df1['number_of_open_complaints'].astype(int)

# df2 -celaning and transformation
df2['number_of_open_complaints'] = df2['number_of_open_complaints'].map(
    functions.clean_open_complaints
)
df2['number_of_open_complaints'] = df2['number_of_open_complaints'].astype(int)

# df3 - cleaning and transformation
df3['number_of_open_complaints'] = df3['number_of_open_complaints'].map(
    functions.clean_open_complaints
)
df3['number_of_open_complaints'] = df3['number_of_open_complaints'].astype(int)

In [20]:
# Gender - and insert U, as unkonwn if we have missing data
# I'm not delete these lines because the insured event, the claim, still exists.

# df1 - [nan, 'F', 'M', 'Femal', 'Male', 'female']
df1['gender'] = df1['gender'].replace({
    'Femal': 'F',
    'Male': 'M',
    'female': 'F',
})
df1['gender'] = df1['gender'].fillna('U')

print(df1['gender'].unique())
print(df1['gender'].value_counts(dropna=False))

# df2 - ['F', 'M', nan, 'female', 'Male']
df2['gender'] = df2['gender'].replace({
    'Femal': 'F',
    'Male': 'M',
    'female': 'F',
})
df2['gender'] = df2['gender'].fillna('U')

print(df2['gender'].unique())
print(df2['gender'].value_counts(dropna=False))

# df3 - ['M', 'F'] - not neccessary to cleaning

print(df3['gender'].unique())
print(df3['gender'].value_counts(dropna=False))

<ArrowStringArray>
['U', 'F', 'M']
Length: 3, dtype: str
gender
U    3054
F     502
M     452
Name: count, dtype: int64
<ArrowStringArray>
['F', 'M', 'U']
Length: 3, dtype: str
gender
F    529
M    462
U      5
Name: count, dtype: int64
<ArrowStringArray>
['M', 'F']
Length: 2, dtype: str
gender
F    3576
M    3494
Name: count, dtype: int64

In [22]:
# State

# df1 - ['Washington',    'Arizona',     'Nevada', 'California',     'Oregon',       'Cali',         'AZ',         'WA',          nan]
# and leave the empty rows
df1['state'] = df1['state'].replace({
    'Cali': 'California',
    'AZ': 'Arizona',
    'WA': 'Washington',
})


print(df1['state'].unique())
print(df1['state'].value_counts(dropna=False))

# df2 - ['Arizona', 'California', 'Oregon', 'Nevada', 'Washington', 'AZ']
df2['state'] = df2['state'].replace({
    'AZ': 'Arizona'
})

print(df2['state'].unique())
print(df2['state'].value_counts(dropna=False))

# df3 - ['Washington', 'Arizona', 'Nevada', 'California', 'Oregon'] - not neccessary to cleaning

print(df3['state'].unique())
print(df3['state'].value_counts(dropna=False))

<ArrowStringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan]
Length: 6, dtype: str
state
NaN           2937
California     331
Oregon         320
Arizona        211
Washington     111
Nevada          98
Name: count, dtype: int64
<ArrowStringArray>
['Arizona', 'California', 'Oregon', 'Nevada', 'Washington']
Length: 5, dtype: str
state
Oregon        303
California    277
Arizona       191
Nevada        125
Washington    100
Name: count, dtype: int64
<ArrowStringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon']
Length: 5, dtype: str
state
California    2544
Oregon        1978
Arizona       1302
Nevada         659
Washington     587
Name: count, dtype: int64

In [24]:
# Education

# df1 - ['Master',             'Bachelor', 'High School or Below', 'College',            'Bachelors',               'Doctor',      nan]
# and leave the empty rows

df1['education'] = df1['education'].replace({
    'Bachelors': 'Bachelor'
})

print(df1['education'].unique())
print(df1['education'].value_counts(dropna=False))

# df2 - ['Bachelor', 'Master', 'College', 'Doctor', 'Bachelors',  'High School or Below']

df1['education'] = df1['education'].replace({
    'Bachelors': 'Bachelor'
})

print(df2['education'].unique())
print(df2['education'].value_counts(dropna=False))

# df3 - ['High School or Below', 'Master', 'Bachelor', 'College', 'Doctor'] - not neccessary to cleaning

print(df3['education'].unique())
print(df3['education'].value_counts(dropna=False))

<ArrowStringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor', nan]
Length: 6, dtype: str
education
NaN                     2937
Bachelor                 331
College                  313
High School or Below     296
Master                    94
Doctor                    37
Name: count, dtype: int64
<ArrowStringArray>
['Bachelor', 'Master', 'College', 'Doctor', 'Bachelors',
 'High School or Below']
Length: 6, dtype: str
education
College                 311
High School or Below    290
Bachelor                243
Master                   86
Doctor                   49
Bachelors                17
Name: count, dtype: int64
<ArrowStringArray>
['High School or Below', 'Master', 'Bachelor', 'College', 'Doctor']
Length: 5, dtype: str
education
Bachelor                2152
College                 2058
High School or Below    2030
Master                   572
Doctor                   258
Name: count, dtype: int64

In [27]:
# vehicle_class - "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"

# df1 - ['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV','Sports Car',    'Luxury Car',             nan]

df1['vehicle_class'] = df1['vehicle_class'].replace({
    'Sports Car': 'Luxury',
    'Luxury SUV': 'Luxury',
    'Luxury Car': 'Luxury',
})


print(df1['vehicle_class'].unique())
print(df1['vehicle_class'].value_counts(dropna=False))

# df2 - ['Four-Door Car',           'SUV',  'Two-Door Car',    'Luxury Car', 'Sports Car',    'Luxury SUV']

df2['vehicle_class'] = df2['vehicle_class'].replace({
    'Sports Car': 'Luxury',
    'Luxury SUV': 'Luxury',
    'Luxury Car': 'Luxury',
})
print(df2['vehicle_class'].unique())
print(df2['vehicle_class'].value_counts(dropna=False))

# df3 [ 'Two-Door Car', 'Four-Door Car',           'SUV',    'Sports Car','Luxury SUV',    'Luxury Car']

df3['vehicle_class'] = df3['vehicle_class'].replace({
    'Sports Car': 'Luxury',
    'Luxury SUV': 'Luxury',
    'Luxury Car': 'Luxury',
})

print(df3['vehicle_class'].unique())
print(df3['vehicle_class'].value_counts(dropna=False))

<ArrowStringArray>
['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan]
Length: 5, dtype: str
vehicle_class
NaN              2937
Four-Door Car     576
Two-Door Car      205
SUV               199
Luxury             91
Name: count, dtype: int64
<ArrowStringArray>
['Four-Door Car', 'SUV', 'Two-Door Car', 'Luxury']
Length: 4, dtype: str
vehicle_class
Four-Door Car    519
Two-Door Car     211
SUV              174
Luxury            92
Name: count, dtype: int64
<ArrowStringArray>
['Two-Door Car', 'Four-Door Car', 'SUV', 'Luxury']
Length: 4, dtype: str
vehicle_class
Four-Door Car    3546
Two-Door Car     1480
SUV              1401
Luxury            643
Name: count, dtype: int64

### Dealing with Null values

In [28]:
print("Missing values per column:")
print('\n')
print(df1.isnull().sum())
print('\n')
print(df2.isnull().sum())
print('\n')
print(df3.isnull().sum())

Missing values per column:


customer                     2937
state                        2937
gender                          0
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints       0
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64


customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      4
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64


customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [29]:
# Since 'customer' appears to be a unique value, I discard the row if it is empty.

df1 = df1.dropna(subset=['customer'])
print(df1.isnull().sum())

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      3
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

### Dealing with duplicates

In [30]:
# Checking the duplicates:

duplicates_count = df1.duplicated().sum()
print(f"Number of duplicated rows before cleaning: {duplicates_count}")

duplicates_count = df2.duplicated().sum()
print(f"Number of duplicated rows before cleaning: {duplicates_count}")

duplicates_count = df3.duplicated().sum()
print(f"Number of duplicated rows before cleaning: {duplicates_count}")

# Since there are no duplicates, there is no action need to do

Number of duplicated rows before cleaning: 0
Number of duplicated rows before cleaning: 0
Number of duplicated rows before cleaning: 0

### Save the clean dataframes

In [31]:
df1.to_csv('df1_cleaned.csv', index=False)
print("\nThe cleaned and formatted dataset saved:'df1_cleaned.csv'")

df2.to_csv('df2_cleaned.csv', index=False)
print("\nThe cleaned and formatted dataset saved:'df2_cleaned.csv'")

df2.to_csv('df3_cleaned.csv', index=False)
print("\nThe cleaned and formatted dataset saved:'df3_cleaned.csv'")

The cleaned and formatted dataset saved:'df1_cleaned.csv'

The cleaned and formatted dataset saved:'df2_cleaned.csv'

The cleaned and formatted dataset saved:'df3_cleaned.csv'

### Merging dataframes

In [33]:
print("Shape of dataframes:")
display(f"Shape df1: {df1.shape}")
display(f"Shape df2: {df2.shape}")
display(f"Shape df3: {df3.shape}")


print("\nInfo about dataframes:")

display(f"Info df1: {df1.info()}")
display(f"Info df2: {df2.info()}")
display(f"Info df3: {df3.info()}")


print("\nIHead of dataframes:")

display(f"Head df1: {df1.head()}")
display(f"Head df2: {df2.head()}")
display(f"Head df3: {df3.head()}")

Shape of dataframes:

'Shape df1: (1071, 11)'

'Shape df2: (996, 11)'

'Shape df3: (7070, 11)'

Info about dataframes:
<class 'pandas.DataFrame'>
RangeIndex: 1071 entries, 0 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   str
 1   state                      1071 non-null   str
 2   gender                     1071 non-null   str
 3   education                  1071 non-null   str
 4   customer_lifetime_value    1068 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   int64
 8   policy_type                1071 non-null   str
 9   vehicle_class              1071 non-null   str
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(4), int64(1), str(6)
memory usage: 145.4 KB

'Info df1: None'

<class 'pandas.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   996 non-null    str
 1   state                      996 non-null    str
 2   gender                     996 non-null    str
 3   education                  996 non-null    str
 4   customer_lifetime_value    992 non-null    float64
 5   income                     996 non-null    int64
 6   monthly_premium_auto       996 non-null    int64
 7   number_of_open_complaints  996 non-null    int64
 8   policy_type                996 non-null    str
 9   vehicle_class              996 non-null    str
 10  total_claim_amount         996 non-null    float64
dtypes: float64(2), int64(3), str(6)
memory usage: 134.5 KB

'Info df2: None'

<class 'pandas.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   7070 non-null   str
 1   state                      7070 non-null   str
 2   gender                     7070 non-null   str
 3   education                  7070 non-null   str
 4   customer_lifetime_value    7070 non-null   float64
 5   income                     7070 non-null   int64
 6   monthly_premium_auto       7070 non-null   int64
 7   number_of_open_complaints  7070 non-null   int64
 8   policy_type                7070 non-null   str
 9   vehicle_class              7070 non-null   str
 10  total_claim_amount         7070 non-null   float64
dtypes: float64(2), int64(3), str(6)
memory usage: 954.5 KB

'Info df3: None'

IHead of dataframes:

'Head df1:   customer       state gender             education  customer_lifetime_value  \\\n0  RB50392  Washington      U                Master                      NaN   \n1  QZ44356     Arizona      F              Bachelor                697953.59   \n2  AI49188      Nevada      F              Bachelor               1288743.17   \n3  WW63253  California      M              Bachelor                764586.18   \n4  GA49547  Washington      M  High School or Below                536307.65   \n\n    income  monthly_premium_auto  number_of_open_complaints     policy_type  \\\n0      0.0                1000.0                          0   Personal Auto   \n1      0.0                  94.0                          0   Personal Auto   \n2  48767.0                 108.0                          0   Personal Auto   \n3      0.0                 106.0                          0  Corporate Auto   \n4  36357.0                  68.0                          0   Personal Auto   \n\n   vehicle_class  total_claim_amount  \n0  Four-Door Car            2.704934  \n1  Four-Door Car         1131.464935  \n2   Two-Door Car          566.472247  \n3            SUV          529.881344  \n4  Four-Door Car           17.269323  '

'Head df2:   customer       state gender education  customer_lifetime_value  income  \\\n0  GS98873     Arizona      F  Bachelor                323912.47   16061   \n1  CW49887  California      F    Master                462680.11   79487   \n2  MY31220  California      F   College                899704.02   54230   \n3  UH35128      Oregon      F   College               2580706.30   71210   \n4  WH52799     Arizona      F   College                380812.21   94903   \n\n   monthly_premium_auto  number_of_open_complaints     policy_type  \\\n0                    88                          0   Personal Auto   \n1                   114                          0    Special Auto   \n2                   112                          0   Personal Auto   \n3                   214                          0   Personal Auto   \n4                    94                          0  Corporate Auto   \n\n   vehicle_class  total_claim_amount  \n0  Four-Door Car               633.6  \n1            SUV               547.2  \n2   Two-Door Car               537.6  \n3         Luxury              1027.2  \n4   Two-Door Car               451.2  '

'Head df3:   customer       state gender             education  customer_lifetime_value  \\\n0  SA25987  Washington      M  High School or Below              3479.137523   \n1  TB86706     Arizona      M                Master              2502.637401   \n2  ZL73902      Nevada      F              Bachelor              3265.156348   \n3  KX23516  California      F  High School or Below              4455.843406   \n4  FN77294  California      M  High School or Below              7704.958480   \n\n   income  monthly_premium_auto  number_of_open_complaints    policy_type  \\\n0       0                   104                          0  Personal Auto   \n1       0                    66                          0  Personal Auto   \n2   25820                    82                          0  Personal Auto   \n3       0                   121                          0  Personal Auto   \n4   30366                   101                          2  Personal Auto   \n\n   vehicle_class  total_claim_amount  \n0   Two-Door Car          499.200000  \n1   Two-Door Car            3.468912  \n2  Four-Door Car          393.600000  \n3            SUV          699.615192  \n4            SUV          484.800000  '

In [34]:
# Shape of dataframes:
# 'Shape df1: (1071, 11)'
# 'Shape df2: (996, 11)'
# 'Shape df3: (7070, 11)'
# it should be: (9137, 11) after the merge

# 1. Stacking datasets
combined_df = pd.concat([df1, df2, df3], axis=0, ignore_index=True)

# 2. Check
print("Combined dataset (rows, columns):", combined_df.shape)
display(combined_df.head())

Combined dataset (rows, columns): (9137, 11)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,U,Master,NaN,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [89]:
import numpy as np
import pandas as pd

url ="https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"
marketing = pd.read_csv(url)


marketing.shape
display(marketing)

marketing.info()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,7,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A,1
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A,1
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,2,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,A,2
10908,10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A,2
10909,10909,IV32877,California,6857.519928,No,Basic,Bachelor,2011-01-08,Unemployed,M,...,3,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,A,1

<class 'pandas.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  str
 2   state                          10910 non-null  str
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  str
 5   coverage                       10910 non-null  str
 6   education                      10910 non-null  str
 7   effective_to_date              10910 non-null  str
 8   employmentstatus               10910 non-null  str
 9   gender                         10910 non-null  str
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  str
 12  marital_status                 10910 non-null  str
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  str
 19  policy                         10910 non-null  str
 20  renew_offer_type               10910 non-null  str
 21  sales_channel                  10910 non-null  str
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  str
 24  vehicle_size                   10910 non-null  str
 25  vehicle_type                   10910 non-null  str
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), str(17)
memory usage: 3.5 MB

### Column Names Operations

In [46]:
marketing.columns = (
    marketing.columns
    .str.strip()        
    .str.lower()        
    .str.replace(" ", "_")
    .str.replace(":", "")
    
)

marketing = marketing.rename(columns={
    "employmentstatus": "employment_status"
})


marketing = marketing.drop(columns=['unnamed_0'])
# The column named `unnamed:_0` is most likely an index left over from a previous save operation
# as it does not contain any new business-relevant information, I removed it

display(marketing.columns.tolist())

['customer',
 'state',
 'customer_lifetime_value',
 'response',
 'coverage',
 'education',
 'effective_to_date',
 'employment_status',
 'gender',
 'income',
 'location_code',
 'marital_status',
 'monthly_premium_auto',
 'months_since_last_claim',
 'months_since_policy_inception',
 'number_of_open_complaints',
 'number_of_policies',
 'policy_type',
 'policy',
 'renew_offer_type',
 'sales_channel',
 'total_claim_amount',
 'vehicle_class',
 'vehicle_size',
 'vehicle_type',
 'month']

### Cleaning invalid values

In [82]:
display(marketing['effective_to_date'].unique())
display(marketing['effective_to_date'].nunique())

# round 2 decimal:
marketing['customer_lifetime_value'] = marketing['customer_lifetime_value'].round(2)
marketing['total_claim_amount'] = marketing['total_claim_amount'].round(2)

<DatetimeArray>
['2011-02-18 00:00:00', '2011-01-18 00:00:00', '2011-02-10 00:00:00',
 '2011-01-11 00:00:00', '2011-01-17 00:00:00', '2011-02-14 00:00:00',
 '2011-02-24 00:00:00', '2011-01-19 00:00:00', '2011-01-04 00:00:00',
 '2011-01-02 00:00:00', '2011-02-07 00:00:00', '2011-01-31 00:00:00',
 '2011-01-26 00:00:00', '2011-02-28 00:00:00', '2011-01-16 00:00:00',
 '2011-02-26 00:00:00', '2011-02-23 00:00:00', '2011-01-15 00:00:00',
 '2011-02-02 00:00:00', '2011-02-15 00:00:00', '2011-01-24 00:00:00',
 '2011-02-21 00:00:00', '2011-02-22 00:00:00', '2011-01-07 00:00:00',
 '2011-01-28 00:00:00', '2011-02-08 00:00:00', '2011-02-12 00:00:00',
 '2011-02-20 00:00:00', '2011-01-05 00:00:00', '2011-02-19 00:00:00',
 '2011-01-03 00:00:00', '2011-02-03 00:00:00', '2011-01-22 00:00:00',
 '2011-01-23 00:00:00', '2011-02-05 00:00:00', '2011-02-13 00:00:00',
 '2011-01-25 00:00:00', '2011-02-16 00:00:00', '2011-02-01 00:00:00',
 '2011-01-27 00:00:00', '2011-01-12 00:00:00', '2011-01-20 00:00:00',
 '2011-02-06 00:00:00', '2011-02-11 00:00:00', '2011-01-21 00:00:00',
 '2011-01-29 00:00:00', '2011-01-09 00:00:00', '2011-02-09 00:00:00',
 '2011-02-27 00:00:00', '2011-01-01 00:00:00', '2011-02-17 00:00:00',
 '2011-02-25 00:00:00', '2011-01-13 00:00:00', '2011-01-06 00:00:00',
 '2011-02-04 00:00:00', '2011-01-14 00:00:00', '2011-01-10 00:00:00',
 '2011-01-08 00:00:00', '2011-01-30 00:00:00']
Length: 59, dtype: datetime64[us]

59

### Dtype operations

In [81]:
marketing['months_since_last_claim'] = marketing['months_since_last_claim'].astype(int)
marketing['number_of_open_complaints'] = marketing['number_of_open_complaints'].astype(int)
marketing['effective_to_date'] = pd.to_datetime(marketing['effective_to_date'])
# now the format is: 2011-01-30 00:00:00, but I do not want to make more modification, 
# since as I understand if I make more modification (slice, forexample) it can be cause problems
# and this format does not effect the analyzation of data 

print(marketing.dtypes)

customer                                    str
state                                       str
customer_lifetime_value                 float64
response                                    str
coverage                                    str
education                                   str
effective_to_date                datetime64[us]
employment_status                           str
gender                                      str
income                                    int64
location_code                               str
marital_status                              str
monthly_premium_auto                      int64
months_since_last_claim                   int64
months_since_policy_inception             int64
number_of_open_complaints                 int64
number_of_policies                        int64
policy_type                                 str
policy                                      str
renew_offer_type                            str
sales_channel                               str
total_claim_amount                      float64
vehicle_class                               str
vehicle_size                                str
vehicle_type                                str
month                                     int64
dtype: object

### Null Values

In [85]:
print("Missing values per column:")
print(marketing.isnull().sum())

# since everywhere is 0, no action needed

Missing values per column:
customer                         0
state                            0
customer_lifetime_value          0
response                         0
coverage                         0
education                        0
effective_to_date                0
employment_status                0
gender                           0
income                           0
location_code                    0
marital_status                   0
monthly_premium_auto             0
months_since_last_claim          0
months_since_policy_inception    0
number_of_open_complaints        0
number_of_policies               0
policy_type                      0
policy                           0
renew_offer_type                 0
sales_channel                    0
total_claim_amount               0
vehicle_class                    0
vehicle_size                     0
vehicle_type                     0
month                            0
dtype: int64

### Duplicates

In [86]:
duplicates_count = marketing.duplicated().sum()
print(f"Number of duplicated rows before cleaning: {duplicates_count}")

Number of duplicated rows before cleaning: 460

In [87]:
# Number of duplicated rows before cleaning: 460

marketing = marketing.drop_duplicates(keep='first').reset_index(drop=True)
duplicates_count = marketing.duplicated().sum()
print(f"Number of duplicated rows after cleaning: {duplicates_count}")

Number of duplicated rows after cleaning: 0

### Duplicates

In [90]:
marketing.to_csv('marketing_cleaned_data.csv', index=False)
print("\nThe cleaned and formatted dataset saved:'marketing_cleaned_data.csv'")

The cleaned and formatted dataset saved:'marketing_cleaned_data.csv'

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [92]:
# 1. Pivot table for aggregation by sales_channel
revenue_by_channel = marketing.pivot_table(
    index='sales_channel',
    values='total_claim_amount',  # vagy monthly_premium_auto
    aggfunc='sum'
).round(2)

# Sort in descending order by highest revenue
revenue_by_channel = revenue_by_channel.sort_values(by='total_claim_amount', ascending=False)

display(revenue_by_channel)

               total_claim_amount
sales_channel
Agent                  1810226.82
Branch                 1301204.00
Call Center             926600.82
Web                     706600.04

*** Dominance of Agent Channel: The Agent channel generates the highest total claim amount by far (over 1.81 million), indicating that personalized, human-driven sales and customer management handle the largest volume of high-value policies or claims.   

*** Traditional vs. Digital Channels: Traditional offline channels (Agent and Branch) account for the vast majority of the total claim amounts, significantly outperforming remote and digital touchpoints.   

*** Lower Digital Engagement: The Web channel records the lowest total claim amount (~706,600), suggesting lower customer adoption, smaller policy sizes, or simpler products being processed online compared to traditional methods.   

*** Strategic Recommendation: Management should investigate ways to boost digital channel adoption (Web) to capture more online market share, while ensuring continued support for the high-performing Agent and Branch networks.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [ ]:
# Your code goes here